# Generated by Django 4.2 on 2023-04-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_desc_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phone',
            new_name='phone',
        ),
    ]
